name: Publish package to GitHub Packages

on:
  release:
    types: [created]
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: macos-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ATOKEN }}

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Check Commit message
        run: |
          commit_message=$(git log -1 --pretty=%B)
          if [[ $commit_message == *"release"* ]]; then
              echo "commit is $commit_message"
          else
              echo "your commit is not release"
              exit 1
          fi        

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - uses: actions/cache@v2
        with:
           path: |
             ~/.gradle/caches
              ~/.gradle/wrapper
           key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/*.properties') }}
           restore-keys: |
             ${{ runner.os }}-gradle-  

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Generate Gradle Properties
        run: ./gradlew generateGradleProperties --no-configuration-cache

      - name: Publish packages
        run: |
          ./gradlew publish
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.ATOKEN }}

#      - name: Publish package
#        uses: gradle/actions/setup-gradle@v3
#        with:
#          arguments: libKMP:publish
#        env:
#          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
#          GITHUB_TOKEN: ${{ secrets.ATOKEN  }}